import { VerticalBox, HorizontalBox, ComboBox } from "std-widgets.slint";

import "SourceHanSansSC-Normal-Min.ttf";

export component MainWindow inherits Window {
    in property <image> bg-image: @image-url("47135233.png");
    in-out property <string> title-text: "顶部状态栏文本";
    in-out property <string> body-text: "你好，这是中文测试文本。hello, this is english test txt";
    in-out property <string> bottom-text: "底部信息栏文本";
    in-out property <string> font-family: "Source Han Sans SC Normal"; // 字体名称需与 TTF 内部的字体名一致
    VerticalBox {
        spacing: 1px;

        // 顶部状态栏
        Rectangle {
            height: 10%;
            background: #2c3e50;
            Text {
                text: root.title-text;
                font-family: root.font-family;
                color: #ffffff;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        // 中间可视化区域
        Rectangle {
            height: 70%;
            background: #ffffff;
            Image {
                source: bg-image;
                image-fit: cover;
                image-rendering: smooth;
            }

            VerticalBox {
                padding: 3px;
                alignment: center;
                Text {
                    text: root.body-text;
                    font-family: root.font-family;
                    font-size: 20px;
                    color: #000000;
                    horizontal-alignment: center;
                    wrap: TextWrap.word-wrap;
                }
            }
        }

        // 底部信息栏
        Rectangle {
            height: 10%;
            background: #2c3e50;
            Text {
                text: root.bottom-text;
                font-family: root.font-family;
                color: #ffffff;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}
